import React from 'react';
import Head from 'next/head';

import DatePicker from '../components/DatePicker';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p className="text-6xl font-bold">matter-of-time</p>
        <p className="text-2xl font-bold">When did you born?</p>
        <DatePicker />
      </div>
    </>
  );
}
