import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import DatePicker from '../components/DatePicker';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-sm mx-auto flex items-center flex-col pb-10">
        <Image src={'/1.webp'} width={500} height={500} alt="logo" />
        <p className="text-3xl font-bold ">matter-of-time</p>
        <p className="text-lg">When did you born?🔮</p>
        <DatePicker />
      </div>
    </>
  );
}
